image:
  repository: "docker.elastic.co/elasticsearch/elasticsearch-oss"
  tag: "6.8.7"
  pullPolicy: "IfNotPresent"

cluster:
  env:
    # IMPORTANT: https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#minimum_master_nodes
    # To prevent data loss, it is vital to configure the discovery.zen.minimum_master_nodes setting so that each master-eligible
    # node knows the minimum number of master-eligible nodes that must be visible in order to form a cluster.
    MINIMUM_MASTER_NODES: "1"
    EXPECTED_MASTER_NODES: "1"
    RECOVER_AFTER_MASTER_NODES: "1"

client:
  replicas: 1

  resources:
    limits:
      cpu: "1"
      memory: "1024Mi"
    requests:
      cpu: "0.25"
      memory: "256Mi"

master:
  replicas: 1
  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    name: data
    size: "128Mi"
  resources:
    limits:
      cpu: "1"
      memory: "1024Mi"
    requests:
      cpu: "0.25"
      memory: "256Mi"

data:
  replicas: 1
  heapSize: "300m"
  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    name: data
    size: "128Mi"
  resources:
    limits:
      cpu: "1.0"
      memory: "2048Mi"
    requests:
      cpu: "0.25"
      memory: "256Mi"
