image: "docker.elastic.co/kibana/kibana-oss"
# we probably want to version match against the stack on the kibana version just in case
imageTag: "7.7.0"

# lower the requirement to just run
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "500m"
    memory: "300Mi"