apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: '1'
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-server.monitoring.svc.cluster.local
---
apiVersion: v1
data:
  admin-user: YWRtaW4=
  admin-password: Z3JhZmFuYQ==
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
type: Opaque