#sidecar:
#  datasources:
#    enabled: true

#dashboards:
#  default:
#    prometheus-stats:
#      # Ref: https://grafana.com/dashboards/2
#      gnetId: 2
#      revision: 2
#      datasource: Prometheus

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local:9090
      access: proxy
      isDefault: true

dashboards:
  id-provider:
    prometheus-dashboard:
      gnetId: 10000
      revision: 1
      datasource: Prometheus
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'id-provider'
        orgId: 1
        folder: ''
        type: file
        updateIntervalSeconds: 30
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/id-provider

admin:
  existingSecret: grafana-secret