## Define serviceAccount names for components. Defaults to component's fully qualified name.
##
serviceAccounts:
  alertmanager:
    create: false
    name:
  nodeExporter:
    create: true
    name:
  pushgateway:
    create: false
    name:
  server:
    create: true
    name:

kubeStateMetrics:
  enabled: false

alertmanager:
  enabled: false

nodeExporter:
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      effect: "NoSchedule"

server:
  ## Prometheus server container name
  ##
  enabled: true
  name: server
  sidecarContainers:

  service:
    servicePort: 9090
  ## Prometheus server container image
  ##
  image:
    repository: prom/prometheus
    tag: v2.16.0
    pullPolicy: IfNotPresent

  global:
    ## How frequently to scrape targets by default
    ##
    scrape_interval: 20s
    ## How long until a scrape request times out
    ##
    scrape_timeout: 10s
    ## How frequently to evaluate rules
    ##
    evaluation_interval: 1m

  persistentVolume:
    ## If true, Prometheus server will create/use a Persistent Volume Claim
    ## If false, use emptyDir
    ##
    enabled: false

pushgateway:
  ## If false, pushgateway will not be installed
  ##
  enabled: false

  persistentVolume:
    ## If true, pushgateway will create/use a Persistent Volume Claim
    ## If false, use emptyDir
    ##
    enabled: false