apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: local-cluster
servers: 1
agents: 2
image: rancher/k3s:v1.20.15-k3s1
registries:
  create:
    name: k3d-registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"
