# To decrease the number of replica as much as possible to give our laptop a chance
replicas: 1
minimumMasterNodes: 1

clusterName: "elasticsearch"
image: "docker.elastic.co/elasticsearch/elasticsearch-oss"
# this is the latest stable release at the time of writing
imageTag: "7.9.0"
# just to make sure we can deploy without clashing when not having a multi-node setup
antiAffinity: "soft"

# Shrink default JVM heap.
esJavaOpts: "-Xmx256m -Xms256m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
  limits:
    cpu: "1000m"

# Let's assume we don't want to persist data given that we will tear this down anyway
persistence:
  enabled: false
